### ISSUE TITLE
Different tables with the same primary key

### ISSUE THREAD

**Issue by AyinawuT** [Open-Earth-Foundation/OpenClimate-Schema#13]
The tables ActorIdentifier, ActorName, TerritoryContext and OrganizationsContext have the same primary key actor_id. Though this is allowed, it is bad design. I would suggest having the actor_id as the primary key in the Actor table, but as foreign keys in the ActorIdentifier, ActorName, TerritoryContext and OrganizationsContext, with these tables having their own primary keys.

**Comment by evanp** [comment]
This is pretty common for a one-or-none relationship.
