### ISSUE TITLE
Document "is_part_of" relationship

### ISSUE THREAD

**Issue by evanp** [Open-Earth-Foundation/OpenClimate-Schema#4]
We have a relationship between actors, `is_part_of`, for use in geographical hierarchies. A city is_part_of a subnational division like a state or province which is_part_of a nation-state.

**Comment by AyinawuT** [comment]
There should be a tables representing the geographical hierarchies that an actor has a relationship with. These tables will have the primary keys of that particular table which can then be represented as a foreign key "is_part_of" in the actor table.

**Comment by evanp** [comment]
I don't think that's the case; I think this is a foreign key back to the Actor table. So, Quebec is_part_of Canada; we'd have two rows like this:

| actor_id | type | is_part_of |
| -------- | ---- | ---------- |
| CA       |  country | EARTH |
| CA-QC | adm1 | CA |
