### ISSUE TITLE
Document is_owned_by relationship

### ISSUE THREAD

**Issue by evanp** [Open-Earth-Foundation/OpenClimate-Schema#5]
One type of actor is an emissions site, like an office building, factory, farm or mine. These actors are usually in a place (like a city or a province), but sometimes they have a relationship to a larger organization, like a corporation or government. The is_owned_by relationship should allow a relationship of ownership or responsibility that's not about geographical boundaries.

**Comment by AyinawuT** [comment]
There should be a table representing the larger organizations that an actor has a relationship with. This table will have the primary keys of the larger organizations which can then be represented as a foreign key "is_owned_by" in the actor table.
