### ISSUE TITLE
Add `url` and `summary` to `Targets` table

### ISSUE THREAD

**Issue by lgloege** [Open-Earth-Foundation/OpenClimate-Schema#51]
We need to add 
1. `tag` to capture to conditionality (conditional versus unconditional contribution) and scenario target years (e.g. BAU)
2. `url` will capture a link to the official document (e.g. NDC a country submitted to UNFCCC)
3. `summary` this will capture a terse plain language summary of the official document in a few sentences.

**Comment by evanp** [comment]
Hi! We won't add a `tag` column. We'll have a separate table, `TargetTag`, for the many-to-many relationship. I'll update when done!
